apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "workflow-shared-service.fullname" . }}-backend
  labels:
    {{- include "workflow-shared-service.labels" . | nindent 4 }}
stringData:
  DJANGO_SECRET_KEY: {{ .Values.backend.secret.DJANGO_SECRET_KEY | quote }}
