apiVersion: v1
kind: Service
metadata:
  name: {{ include "workflow-shared-service.fullname" . }}-backend
  labels:
    {{- include "workflow-shared-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "workflow-shared-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
