# Generated by Django 6.0.1 on 2026-01-29 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_workflow_instances'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=120)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('task_type', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('actor_identity', models.CharField(blank=True, max_length=200)),
                ('action', models.CharField(blank=True, max_length=200)),
                ('action_data', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.tenant')),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='core.workflowinstance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTaskCompletionIdempotency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=200)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.tenant')),
                ('user_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to='core.usertask')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='usertask',
            constraint=models.UniqueConstraint(fields=('tenant', 'workflow_instance', 'task_id'), name='uniq_user_task_per_instance'),
        ),
        migrations.AddConstraint(
            model_name='usertaskcompletionidempotency',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uniq_user_task_idempotency_per_tenant'),
        ),
    ]
