# Generated by Django 6.0.1 on 2026-01-29 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_service_tasks"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("definition_upload", "Definition Upload"),
                            ("instance_start", "Instance Start"),
                            ("user_task_complete", "User Task Complete"),
                            ("service_task_start", "Service Task Start"),
                            ("service_task_callback", "Service Task Callback"),
                        ],
                        max_length=120,
                    ),
                ),
                ("actor_identity", models.CharField(blank=True, max_length=200)),
                ("correlation_id", models.CharField(blank=True, max_length=200)),
                ("business_key", models.CharField(blank=True, max_length=200)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "definition_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="core.workflowdefinitionversion",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="core.tenant",
                    ),
                ),
                (
                    "workflow_instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="core.workflowinstance",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant", "workflow_instance"],
                        name="core_audite_tenant__b766ab_idx",
                    ),
                    models.Index(
                        fields=["tenant", "business_key"],
                        name="core_audite_tenant__036a6c_idx",
                    ),
                    models.Index(
                        fields=["tenant", "correlation_id"],
                        name="core_audite_tenant__79f3e2_idx",
                    ),
                    models.Index(
                        fields=["tenant", "created_at"],
                        name="core_audite_tenant__b7d570_idx",
                    ),
                ],
            },
        ),
    ]
