# Generated by Django 6.0.1 on 2026-01-30 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_servicetask_status_auditevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowdefinition',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='WorkflowGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.workflowgroup')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='workflowdefinition',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='definitions', to='core.workflowgroup'),
        ),
        migrations.AddConstraint(
            model_name='workflowgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('tenant', 'name'), name='uniq_root_workflow_group_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='workflowgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('tenant', 'parent', 'name'), name='uniq_workflow_group_name_per_parent_per_tenant'),
        ),
    ]
